### ISSUE TITLE
Add Accredify on the Works Page

### ISSUE THREAD

**Issue by matheusbras** [Helabs/helabs.github.com#473]
Guys, we need to add Accredify as a client on the work page. What do you guys need? A screenshot? Or just the URL?

cc/ @thiagonzalez @mikaelcarrara

**Comment by mergulhao** [comment]
@marcioc0sta Can you take a look?

**Comment by marcioc0sta** [comment]
@mergulhao I'll contact @RafaelEsberard and ask him to provide the necessary information about the project

**Comment by marcioc0sta** [comment]
Can i close this issue?
