### ISSUE TITLE
Services page

### ISSUE THREAD

**Issue by beatrizcp87** [Helabs/helabs.github.com#519]
Hey, investment week here too.  I couldn't find anyone to help today so I started to analyze our stuff and develop some proposals for improvement. (only visual proposal, no PR yet)

The "services pages" was a kind of "heavy" for me so I try to make it "lighter".

(the original)
![screen shot 2014-12-08 at 6 19 33 pm](https://cloud.githubusercontent.com/assets/5721795/5346415/dc8e971e-7f06-11e4-835d-312f3b5049e5.png)

And also I think we have some front-end problem on this page when using big screens: 
(align problem)
![screen shot 2014-12-08 at 6 20 57 pm](https://cloud.githubusercontent.com/assets/5721795/5346432/081f1228-7f07-11e4-88d4-1667e191c6e7.png)

_____

Proposal

I changed the fonts size and the text width for improve the read. 

![proposal](https://cloud.githubusercontent.com/assets/5721795/5346329/16570a68-7f06-11e4-8644-f15edfa0c037.png)

Also I added some elements, I'm not sure if the blog links would be a good experience, but here is the proposal. 

What do you think?

**Comment by mergulhao** [comment]
@marcioc0sta can you take a look here?

**Comment by marcioc0sta** [comment]
@mergulhao on it!

**Comment by mergulhao** [comment]
@marcioc0sta what happened here?

**Comment by marcioc0sta** [comment]
@mergulhao I started this, make a stop to do other stuff and i'll return.

**Comment by marcioc0sta** [comment]
@mergulhao i'm heading back for this now.

**Comment by beatrizcp87** [comment]
On it

**Comment by beatrizcp87** [comment]
I didn't have time to this yet and nobody even miss this page refactoring yet. I belive that means that isn't priority anymore and soon we will do the site redesign, so I'm closing this issue.
