### ISSUE TITLE
Improve startupdev contact form result

### ISSUE THREAD

**Issue by mergulhao** [Helabs/helabs.github.com#539]
We have a submit form here: http://helabs.com.br/servicos/startupdev/

When this form is submited, it's saved on Wufoo and it return the user browser to http://helabs.com.br/servicos/startupdev/#public

When ``#public`` anchor is detected, it show us an alert with a message. We should remove this default alert and add a better answer to our users. It can be a modal or something else. Use your imagination.

Ask me if you have any doubts.

**Comment by matheusagcosta** [comment]
@mergulhao on it.

**Comment by matheusagcosta** [comment]
@mergulhao What do you say?

![screen shot 2015-01-16 at 17 05 55](https://cloud.githubusercontent.com/assets/3741582/5782437/ff407408-9da1-11e4-80de-bb78a1c29263.png)

**Comment by mergulhao** [comment]
@matheusagcosta Cool. I think we can remove the "X" on the up-left. The "Voltar" should be "Ok" in PT version and "Dismiss" in EN version.

**Comment by matheusagcosta** [comment]
@mergulhao it's done.

Anything else?

![screen shot 2015-01-16 at 18 27 02](https://cloud.githubusercontent.com/assets/3741582/5783785/4b56cc4c-9dad-11e4-9463-89581b8779aa.png)

**Comment by mergulhao** [comment]
Show!
