### ISSUE TITLE
Add negociosbrasil.com.br to the helabs.com/pt/servicos/startupdev/

### ISSUE THREAD

**Issue by eduardofiorezi** [Helabs/helabs.github.com#551]
Please add that startupdev

@beatrizcp87 @guiloyins or @aneziocampos

**Comment by helabstech** [comment]
Added the project description, testimonial and the screenshot from negociosbrasil.com.br

Descrição: Plataforma para compra e venda de empresas
Description: Platform to buy and sell companies

> Olá Bia,
> 
> Ficamos bem satisfeitos com o resultado apresentado, pois reproduziu exatamente o que precisávamos desenvolver para validar nosso modelo de negócio. Recebemos boas ideias e dicas que contribuíram bastante para a formulação dessa ideia final. Podemos dizer que estamos aptos a trabalhar em busca de nossos clientes, agora que temos um sistema funcional e adequado as nossas necessidades. É bem provável que escolheremos novamente essa equipe para darmos continuidade ao projeto conforme formos obtendo sucesso.

![negocios_brasil](https://cloud.githubusercontent.com/assets/3330632/6083494/20e79400-ae10-11e4-864f-8b313e54425d.png)

**Comment by beatrizcp87** [comment]
I'll do this today.

**Comment by beatrizcp87** [comment]
PR #559

**Comment by mikaelcarrara** [comment]
Send that improvs as a new PR please.

**Comment by beatrizcp87** [comment]
já tá no site.
