### ISSUE TITLE
Add Oswaldo profile

### ISSUE THREAD

**Issue by eduardofiorezi** [Helabs/helabs.github.com#560]
Hi @oswaldoferreira,

As your fist action, please make a pull request with your profile in PT-BR and EN

**Comment by oswaldoferreira** [comment]
Since @mikaelcarrara told me that would happen a huge merge involving HE:mobile profiles, he said to wait for that before finishing this issue. He will personally add my profile after it.

**Comment by mikaelcarrara** [comment]
Yes and the rake task are broken: https://github.com/Helabs/helabs.github.com/issues/561
