### ISSUE TITLE
Novos forms

### ISSUE THREAD

**Issue by mikaelcarrara** [Helabs/helabs.github.com#594]
Aceitei a PR do @rafaelp hoje:
https://github.com/Helabs/helabs.github.com/pull/593

Os forms não bateram com os que estavam no Wufoo então eu tive que dar rollback.

@beatrizcp87 Amanhã confere esses campos nesses forms do wufoo para as telas:

- orcamento.html
- contratar.html

Depois pega o idstamp certo e atualiza nas views pra enviar corretamente.

Não sei agora como aceitar essa PR agora que dei rollback.
Peça ajuda de algum dev, pois estarei em planning da Monashees.

Obrigado, abs!

**Comment by beatrizcp87** [comment]
@mikaelcarrara essa é a parada que o rafael lima disse que já tinha resolvido cara?

**Comment by rafaelp** [comment]
Está resolvido!

**Comment by marciovsena** [comment]
Visto que está resolvido, estou fechando.
