### ISSUE TITLE
Link "Voltar para página inicial." doesn't works after contact form submit

### ISSUE THREAD

**Issue by mergulhao** [Helabs/helabs.github.com#596]
Access here:
http://helabs.com/pt/fale-conosco/contratar-enviado/#public

Or here:
http://helabs.com/pt/fale-conosco/orcamento-enviado/#public

Click the link:
"« Voltar para página inicial."

Result:
You go to a blank page. :open_mouth::open_mouth::open_mouth:

Not high priority, but annoying to people who submit our forms.

**Comment by beatrizcp87** [comment]
I will send to marketing issues because you didn't assign anyone and this week we are still chosing que new maintainner of HE:labs site.

**Comment by mergulhao** [comment]
Correct link: http://helabs.com/pt/fale-conosco/proposta-enviada/#public

**Comment by marciovsena** [comment]
@mergulhao pretendo verificar esse erro na segunda-feira, visto que é o meu dia mais tranquilo. Até mesmo já criei um branch para resolução.
