### ISSUE TITLE
Error found in the Team page

### ISSUE THREAD

**Issue by marciovsena** [Helabs/helabs.github.com#615]
Firefox browser: Error found in the Team page. When you change the language to the images are not loading.
![captura de tela 2015-07-02 as 19 14 37](https://cloud.githubusercontent.com/assets/3450717/8489109/9c322250-20ee-11e5-8a64-ac7fd5b8175a.png)

**Comment by beatrizcp87** [comment]
Did you fix it? @marciovsena

**Comment by marciovsena** [comment]
Not correct yet. @beatrizcp87

**Comment by marciovsena** [comment]
Fix and waiting merge #619

**Comment by marcioj** [comment]
Closing since #619 is already merged
