### ISSUE TITLE
I need a code review on this commit

### ISSUE THREAD

**Issue by beatrizcp87** [Helabs/helabs.github.com#616]
Commit: 5377ae55ba5ec184a74f03385b7d68785e6dfc68
https://github.com/Helabs/helabs.github.com/commit/5377ae55ba5ec184a74f03385b7d68785e6dfc68

I'm not sure if this is the right way to do this fix.
The problem was: the feedback modal (after complete the form) wasn't appering on safari.
Now it's working but I don't now if is the best way to do this. 

Please check the commit.

**Comment by marciovsena** [comment]
@ beatrizcp87 would also do well, running and following a solution I found here as well.
