### ISSUE TITLE
Team member maps error link

### ISSUE THREAD

**Issue by magdielsilva** [Helabs/helabs.github.com#672]
There is an incorrect link on the map team in the English version.
This "job" tag is not closed.

![jig2npb](https://cloud.githubusercontent.com/assets/13033151/10589105/2f39c58c-7688-11e5-98c4-03193657c478.png)
![lg59hkg](https://cloud.githubusercontent.com/assets/13033151/10589106/2f3bdb88-7688-11e5-94c3-2f72aa47efb8.png)

**Comment by rodrigopinto** [comment]
@magdielsilva Maybe this tag should be entirely removed. Look at the 705 line, `li` tag has `display: none;` on en page and is not being displayed. Could you confirm, if it is correct.

**Comment by TiuTalk** [comment]
@rodrigopinto and when we have open jobs again? I think we should keep the tag and just fix the markup

**Comment by magdielsilva** [comment]
I'am closing de tag </a> in line 49 (our-team.html) like Nosso-Time BR version to fix this problem and it works fine!

**Comment by rodrigopinto** [comment]
@magdielsilva @TiuTalk  :+1:
